// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currentuser.proto

package hiber

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Your personal data
type CurrentUser struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// The organizations that this user has access to.
	Organizations []string `protobuf:"bytes,4,rep,name=organizations" json:"organizations,omitempty"`
	// The default organization for this user.
	DefaultOrganization string `protobuf:"bytes,5,opt,name=default_organization,json=defaultOrganization" json:"default_organization,omitempty"`
	// Open access requests.
	RequestedOrganizations []string `protobuf:"bytes,6,rep,name=requested_organizations,json=requestedOrganizations" json:"requested_organizations,omitempty"`
	// The current organization for this user.
	// If this is a user, this equals the default_organization.
	// If this is a token, it's the token's organization.
	CurrentOrganization string `protobuf:"bytes,8,opt,name=current_organization,json=currentOrganization" json:"current_organization,omitempty"`
	// Permissions for the current organization.
	CurrentOrganizationPermissions *Filter_OrganizationPermissions `protobuf:"bytes,9,opt,name=current_organization_permissions,json=currentOrganizationPermissions" json:"current_organization_permissions,omitempty"`
	// Permissions for the user. If this is a token, the user permissions may be limited.
	UserPermissions        *Filter_UserPermissions `protobuf:"bytes,10,opt,name=user_permissions,json=userPermissions" json:"user_permissions,omitempty"`
	MissionControlSettings string                  `protobuf:"bytes,11,opt,name=mission_control_settings,json=missionControlSettings" json:"mission_control_settings,omitempty"`
	// Whether the user accepted the terms and conditions.
	AcceptedTac bool `protobuf:"varint,12,opt,name=accepted_tac,json=acceptedTac" json:"accepted_tac,omitempty"`
}

func (m *CurrentUser) Reset()                    { *m = CurrentUser{} }
func (m *CurrentUser) String() string            { return proto.CompactTextString(m) }
func (*CurrentUser) ProtoMessage()               {}
func (*CurrentUser) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *CurrentUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CurrentUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CurrentUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CurrentUser) GetOrganizations() []string {
	if m != nil {
		return m.Organizations
	}
	return nil
}

func (m *CurrentUser) GetDefaultOrganization() string {
	if m != nil {
		return m.DefaultOrganization
	}
	return ""
}

func (m *CurrentUser) GetRequestedOrganizations() []string {
	if m != nil {
		return m.RequestedOrganizations
	}
	return nil
}

func (m *CurrentUser) GetCurrentOrganization() string {
	if m != nil {
		return m.CurrentOrganization
	}
	return ""
}

func (m *CurrentUser) GetCurrentOrganizationPermissions() *Filter_OrganizationPermissions {
	if m != nil {
		return m.CurrentOrganizationPermissions
	}
	return nil
}

func (m *CurrentUser) GetUserPermissions() *Filter_UserPermissions {
	if m != nil {
		return m.UserPermissions
	}
	return nil
}

func (m *CurrentUser) GetMissionControlSettings() string {
	if m != nil {
		return m.MissionControlSettings
	}
	return ""
}

func (m *CurrentUser) GetAcceptedTac() bool {
	if m != nil {
		return m.AcceptedTac
	}
	return false
}

// Get your personal data
type CurrentUserRequest struct {
}

func (m *CurrentUserRequest) Reset()                    { *m = CurrentUserRequest{} }
func (m *CurrentUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrentUserRequest) ProtoMessage()               {}
func (*CurrentUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

// Request access to an organization by name, if it exists.
// You request will be saved and the organization owner notified.
// Organization admins can approve or reject your request.
type RequestAccessRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *RequestAccessRequest) Reset()                    { *m = RequestAccessRequest{} }
func (m *RequestAccessRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestAccessRequest) ProtoMessage()               {}
func (*RequestAccessRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *RequestAccessRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type RequestAccessRequest_Response struct {
}

func (m *RequestAccessRequest_Response) Reset()         { *m = RequestAccessRequest_Response{} }
func (m *RequestAccessRequest_Response) String() string { return proto.CompactTextString(m) }
func (*RequestAccessRequest_Response) ProtoMessage()    {}
func (*RequestAccessRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{2, 0}
}

// Cancel a previously made access request.
type CancelAccessRequestRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *CancelAccessRequestRequest) Reset()                    { *m = CancelAccessRequestRequest{} }
func (m *CancelAccessRequestRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelAccessRequestRequest) ProtoMessage()               {}
func (*CancelAccessRequestRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *CancelAccessRequestRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type CancelAccessRequestRequest_Response struct {
}

func (m *CancelAccessRequestRequest_Response) Reset()         { *m = CancelAccessRequestRequest_Response{} }
func (m *CancelAccessRequestRequest_Response) String() string { return proto.CompactTextString(m) }
func (*CancelAccessRequestRequest_Response) ProtoMessage()    {}
func (*CancelAccessRequestRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{3, 0}
}

// Delete yourself.
// Removes all login information and personal data, except for you email address for auditing purposes.
type DeleteCurrentUserRequest struct {
}

func (m *DeleteCurrentUserRequest) Reset()                    { *m = DeleteCurrentUserRequest{} }
func (m *DeleteCurrentUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCurrentUserRequest) ProtoMessage()               {}
func (*DeleteCurrentUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

type DeleteCurrentUserRequest_Response struct {
}

func (m *DeleteCurrentUserRequest_Response) Reset()         { *m = DeleteCurrentUserRequest_Response{} }
func (m *DeleteCurrentUserRequest_Response) String() string { return proto.CompactTextString(m) }
func (*DeleteCurrentUserRequest_Response) ProtoMessage()    {}
func (*DeleteCurrentUserRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{4, 0}
}

// Set the default organization to use when it is not specified in the call.
// Note: this can be a child organization of one of the owned organizations.
type UpdateDefaultOrganizationRequest struct {
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *UpdateDefaultOrganizationRequest) Reset()         { *m = UpdateDefaultOrganizationRequest{} }
func (m *UpdateDefaultOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDefaultOrganizationRequest) ProtoMessage()    {}
func (*UpdateDefaultOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{5}
}

func (m *UpdateDefaultOrganizationRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type UpdateDefaultOrganizationRequest_Response struct {
	DefaultOrganization string `protobuf:"bytes,1,opt,name=default_organization,json=defaultOrganization" json:"default_organization,omitempty"`
}

func (m *UpdateDefaultOrganizationRequest_Response) Reset() {
	*m = UpdateDefaultOrganizationRequest_Response{}
}
func (m *UpdateDefaultOrganizationRequest_Response) String() string { return proto.CompactTextString(m) }
func (*UpdateDefaultOrganizationRequest_Response) ProtoMessage()    {}
func (*UpdateDefaultOrganizationRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{5, 0}
}

func (m *UpdateDefaultOrganizationRequest_Response) GetDefaultOrganization() string {
	if m != nil {
		return m.DefaultOrganization
	}
	return ""
}

// Update mission control settings, which are in a json format.
type UpdateMissionControlSettingsRequest struct {
	Update string `protobuf:"bytes,1,opt,name=update" json:"update,omitempty"`
}

func (m *UpdateMissionControlSettingsRequest) Reset()         { *m = UpdateMissionControlSettingsRequest{} }
func (m *UpdateMissionControlSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMissionControlSettingsRequest) ProtoMessage()    {}
func (*UpdateMissionControlSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{6}
}

func (m *UpdateMissionControlSettingsRequest) GetUpdate() string {
	if m != nil {
		return m.Update
	}
	return ""
}

type UpdateMissionControlSettingsRequest_Response struct {
	MissionControlSettings string `protobuf:"bytes,1,opt,name=mission_control_settings,json=missionControlSettings" json:"mission_control_settings,omitempty"`
}

func (m *UpdateMissionControlSettingsRequest_Response) Reset() {
	*m = UpdateMissionControlSettingsRequest_Response{}
}
func (m *UpdateMissionControlSettingsRequest_Response) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateMissionControlSettingsRequest_Response) ProtoMessage() {}
func (*UpdateMissionControlSettingsRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{6, 0}
}

func (m *UpdateMissionControlSettingsRequest_Response) GetMissionControlSettings() string {
	if m != nil {
		return m.MissionControlSettings
	}
	return ""
}

type AcceptTermsAndConditionsRequest struct {
	AcceptTac bool `protobuf:"varint,1,opt,name=accept_tac,json=acceptTac" json:"accept_tac,omitempty"`
}

func (m *AcceptTermsAndConditionsRequest) Reset()                    { *m = AcceptTermsAndConditionsRequest{} }
func (m *AcceptTermsAndConditionsRequest) String() string            { return proto.CompactTextString(m) }
func (*AcceptTermsAndConditionsRequest) ProtoMessage()               {}
func (*AcceptTermsAndConditionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *AcceptTermsAndConditionsRequest) GetAcceptTac() bool {
	if m != nil {
		return m.AcceptTac
	}
	return false
}

type AcceptTermsAndConditionsRequest_Response struct {
}

func (m *AcceptTermsAndConditionsRequest_Response) Reset() {
	*m = AcceptTermsAndConditionsRequest_Response{}
}
func (m *AcceptTermsAndConditionsRequest_Response) String() string { return proto.CompactTextString(m) }
func (*AcceptTermsAndConditionsRequest_Response) ProtoMessage()    {}
func (*AcceptTermsAndConditionsRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{7, 0}
}

// List all organizations that can be impersonated.
type AccessibleOrganizationsRequest struct {
}

func (m *AccessibleOrganizationsRequest) Reset()                    { *m = AccessibleOrganizationsRequest{} }
func (m *AccessibleOrganizationsRequest) String() string            { return proto.CompactTextString(m) }
func (*AccessibleOrganizationsRequest) ProtoMessage()               {}
func (*AccessibleOrganizationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

type AccessibleOrganizationsRequest_Response struct {
	Organizations []string `protobuf:"bytes,1,rep,name=organizations" json:"organizations,omitempty"`
}

func (m *AccessibleOrganizationsRequest_Response) Reset() {
	*m = AccessibleOrganizationsRequest_Response{}
}
func (m *AccessibleOrganizationsRequest_Response) String() string { return proto.CompactTextString(m) }
func (*AccessibleOrganizationsRequest_Response) ProtoMessage()    {}
func (*AccessibleOrganizationsRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{8, 0}
}

func (m *AccessibleOrganizationsRequest_Response) GetOrganizations() []string {
	if m != nil {
		return m.Organizations
	}
	return nil
}

func init() {
	proto.RegisterType((*CurrentUser)(nil), "hiber.user.CurrentUser")
	proto.RegisterType((*CurrentUserRequest)(nil), "hiber.user.CurrentUserRequest")
	proto.RegisterType((*RequestAccessRequest)(nil), "hiber.user.RequestAccessRequest")
	proto.RegisterType((*RequestAccessRequest_Response)(nil), "hiber.user.RequestAccessRequest.Response")
	proto.RegisterType((*CancelAccessRequestRequest)(nil), "hiber.user.CancelAccessRequestRequest")
	proto.RegisterType((*CancelAccessRequestRequest_Response)(nil), "hiber.user.CancelAccessRequestRequest.Response")
	proto.RegisterType((*DeleteCurrentUserRequest)(nil), "hiber.user.DeleteCurrentUserRequest")
	proto.RegisterType((*DeleteCurrentUserRequest_Response)(nil), "hiber.user.DeleteCurrentUserRequest.Response")
	proto.RegisterType((*UpdateDefaultOrganizationRequest)(nil), "hiber.user.UpdateDefaultOrganizationRequest")
	proto.RegisterType((*UpdateDefaultOrganizationRequest_Response)(nil), "hiber.user.UpdateDefaultOrganizationRequest.Response")
	proto.RegisterType((*UpdateMissionControlSettingsRequest)(nil), "hiber.user.UpdateMissionControlSettingsRequest")
	proto.RegisterType((*UpdateMissionControlSettingsRequest_Response)(nil), "hiber.user.UpdateMissionControlSettingsRequest.Response")
	proto.RegisterType((*AcceptTermsAndConditionsRequest)(nil), "hiber.user.AcceptTermsAndConditionsRequest")
	proto.RegisterType((*AcceptTermsAndConditionsRequest_Response)(nil), "hiber.user.AcceptTermsAndConditionsRequest.Response")
	proto.RegisterType((*AccessibleOrganizationsRequest)(nil), "hiber.user.AccessibleOrganizationsRequest")
	proto.RegisterType((*AccessibleOrganizationsRequest_Response)(nil), "hiber.user.AccessibleOrganizationsRequest.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CurrentUserService service

type CurrentUserServiceClient interface {
	CurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUser, error)
	RequestAccess(ctx context.Context, in *RequestAccessRequest, opts ...grpc.CallOption) (*RequestAccessRequest_Response, error)
	CancelAccessRequest(ctx context.Context, in *CancelAccessRequestRequest, opts ...grpc.CallOption) (*CancelAccessRequestRequest_Response, error)
	DeleteCurrentUser(ctx context.Context, in *DeleteCurrentUserRequest, opts ...grpc.CallOption) (*DeleteCurrentUserRequest_Response, error)
	UpdateDefaultOrganization(ctx context.Context, in *UpdateDefaultOrganizationRequest, opts ...grpc.CallOption) (*UpdateDefaultOrganizationRequest_Response, error)
	UpdateMissionControlSettings(ctx context.Context, in *UpdateMissionControlSettingsRequest, opts ...grpc.CallOption) (*UpdateMissionControlSettingsRequest_Response, error)
	AcceptTermsAndConditions(ctx context.Context, in *AcceptTermsAndConditionsRequest, opts ...grpc.CallOption) (*AcceptTermsAndConditionsRequest_Response, error)
	AccessibleOrganizations(ctx context.Context, in *AccessibleOrganizationsRequest, opts ...grpc.CallOption) (*AccessibleOrganizationsRequest_Response, error)
}

type currentUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewCurrentUserServiceClient(cc *grpc.ClientConn) CurrentUserServiceClient {
	return &currentUserServiceClient{cc}
}

func (c *currentUserServiceClient) CurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUser, error) {
	out := new(CurrentUser)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/CurrentUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentUserServiceClient) RequestAccess(ctx context.Context, in *RequestAccessRequest, opts ...grpc.CallOption) (*RequestAccessRequest_Response, error) {
	out := new(RequestAccessRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/RequestAccess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentUserServiceClient) CancelAccessRequest(ctx context.Context, in *CancelAccessRequestRequest, opts ...grpc.CallOption) (*CancelAccessRequestRequest_Response, error) {
	out := new(CancelAccessRequestRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/CancelAccessRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentUserServiceClient) DeleteCurrentUser(ctx context.Context, in *DeleteCurrentUserRequest, opts ...grpc.CallOption) (*DeleteCurrentUserRequest_Response, error) {
	out := new(DeleteCurrentUserRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/DeleteCurrentUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentUserServiceClient) UpdateDefaultOrganization(ctx context.Context, in *UpdateDefaultOrganizationRequest, opts ...grpc.CallOption) (*UpdateDefaultOrganizationRequest_Response, error) {
	out := new(UpdateDefaultOrganizationRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/UpdateDefaultOrganization", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentUserServiceClient) UpdateMissionControlSettings(ctx context.Context, in *UpdateMissionControlSettingsRequest, opts ...grpc.CallOption) (*UpdateMissionControlSettingsRequest_Response, error) {
	out := new(UpdateMissionControlSettingsRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/UpdateMissionControlSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentUserServiceClient) AcceptTermsAndConditions(ctx context.Context, in *AcceptTermsAndConditionsRequest, opts ...grpc.CallOption) (*AcceptTermsAndConditionsRequest_Response, error) {
	out := new(AcceptTermsAndConditionsRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/AcceptTermsAndConditions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentUserServiceClient) AccessibleOrganizations(ctx context.Context, in *AccessibleOrganizationsRequest, opts ...grpc.CallOption) (*AccessibleOrganizationsRequest_Response, error) {
	out := new(AccessibleOrganizationsRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.user.CurrentUserService/AccessibleOrganizations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CurrentUserService service

type CurrentUserServiceServer interface {
	CurrentUser(context.Context, *CurrentUserRequest) (*CurrentUser, error)
	RequestAccess(context.Context, *RequestAccessRequest) (*RequestAccessRequest_Response, error)
	CancelAccessRequest(context.Context, *CancelAccessRequestRequest) (*CancelAccessRequestRequest_Response, error)
	DeleteCurrentUser(context.Context, *DeleteCurrentUserRequest) (*DeleteCurrentUserRequest_Response, error)
	UpdateDefaultOrganization(context.Context, *UpdateDefaultOrganizationRequest) (*UpdateDefaultOrganizationRequest_Response, error)
	UpdateMissionControlSettings(context.Context, *UpdateMissionControlSettingsRequest) (*UpdateMissionControlSettingsRequest_Response, error)
	AcceptTermsAndConditions(context.Context, *AcceptTermsAndConditionsRequest) (*AcceptTermsAndConditionsRequest_Response, error)
	AccessibleOrganizations(context.Context, *AccessibleOrganizationsRequest) (*AccessibleOrganizationsRequest_Response, error)
}

func RegisterCurrentUserServiceServer(s *grpc.Server, srv CurrentUserServiceServer) {
	s.RegisterService(&_CurrentUserService_serviceDesc, srv)
}

func _CurrentUserService_CurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).CurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/CurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).CurrentUser(ctx, req.(*CurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentUserService_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/RequestAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).RequestAccess(ctx, req.(*RequestAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentUserService_CancelAccessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAccessRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).CancelAccessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/CancelAccessRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).CancelAccessRequest(ctx, req.(*CancelAccessRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentUserService_DeleteCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).DeleteCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/DeleteCurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).DeleteCurrentUser(ctx, req.(*DeleteCurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentUserService_UpdateDefaultOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDefaultOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).UpdateDefaultOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/UpdateDefaultOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).UpdateDefaultOrganization(ctx, req.(*UpdateDefaultOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentUserService_UpdateMissionControlSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMissionControlSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).UpdateMissionControlSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/UpdateMissionControlSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).UpdateMissionControlSettings(ctx, req.(*UpdateMissionControlSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentUserService_AcceptTermsAndConditions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTermsAndConditionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).AcceptTermsAndConditions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/AcceptTermsAndConditions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).AcceptTermsAndConditions(ctx, req.(*AcceptTermsAndConditionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentUserService_AccessibleOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessibleOrganizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentUserServiceServer).AccessibleOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.user.CurrentUserService/AccessibleOrganizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentUserServiceServer).AccessibleOrganizations(ctx, req.(*AccessibleOrganizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CurrentUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hiber.user.CurrentUserService",
	HandlerType: (*CurrentUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CurrentUser",
			Handler:    _CurrentUserService_CurrentUser_Handler,
		},
		{
			MethodName: "RequestAccess",
			Handler:    _CurrentUserService_RequestAccess_Handler,
		},
		{
			MethodName: "CancelAccessRequest",
			Handler:    _CurrentUserService_CancelAccessRequest_Handler,
		},
		{
			MethodName: "DeleteCurrentUser",
			Handler:    _CurrentUserService_DeleteCurrentUser_Handler,
		},
		{
			MethodName: "UpdateDefaultOrganization",
			Handler:    _CurrentUserService_UpdateDefaultOrganization_Handler,
		},
		{
			MethodName: "UpdateMissionControlSettings",
			Handler:    _CurrentUserService_UpdateMissionControlSettings_Handler,
		},
		{
			MethodName: "AcceptTermsAndConditions",
			Handler:    _CurrentUserService_AcceptTermsAndConditions_Handler,
		},
		{
			MethodName: "AccessibleOrganizations",
			Handler:    _CurrentUserService_AccessibleOrganizations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currentuser.proto",
}

func init() { proto.RegisterFile("currentuser.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0xfd, 0x19, 0x02, 0x24, 0x13, 0xe0, 0x07, 0x4b, 0x04, 0xae, 0x55, 0x68, 0xea, 0x52, 0x94,
	0xfe, 0x33, 0x2d, 0x14, 0x95, 0x4b, 0x0f, 0x21, 0x08, 0x55, 0x15, 0x15, 0xc8, 0xc0, 0xa5, 0xaa,
	0x14, 0x6d, 0xec, 0x69, 0x58, 0xc9, 0xb1, 0xdd, 0x5d, 0xa7, 0x07, 0xa4, 0x4a, 0x95, 0xaa, 0x1e,
	0xfa, 0x25, 0xfa, 0x01, 0xfa, 0x29, 0xab, 0xac, 0x1d, 0xec, 0x25, 0x76, 0x20, 0xbd, 0xd9, 0x33,
	0xcf, 0xef, 0x4d, 0x76, 0xde, 0x5b, 0x05, 0x96, 0x9d, 0x3e, 0xe7, 0xe8, 0x47, 0x7d, 0x81, 0xdc,
	0x0a, 0x79, 0x10, 0x05, 0x04, 0x2e, 0x59, 0x07, 0xb9, 0x35, 0xa8, 0x18, 0xd0, 0xa1, 0x02, 0xe3,
	0xba, 0xf9, 0xa7, 0x04, 0xd5, 0x56, 0x8c, 0xbe, 0x10, 0xc8, 0xc9, 0x22, 0x4c, 0x31, 0x57, 0xd7,
	0xea, 0x5a, 0xa3, 0x62, 0x4f, 0x31, 0x97, 0xd4, 0x60, 0x06, 0x7b, 0x94, 0x79, 0xfa, 0x94, 0x2c,
	0xc5, 0x2f, 0x84, 0x40, 0xc9, 0xa7, 0x3d, 0xd4, 0xa7, 0x65, 0x51, 0x3e, 0x93, 0x4d, 0x58, 0x08,
	0x78, 0x97, 0xfa, 0xec, 0x8a, 0x46, 0x2c, 0xf0, 0x85, 0x5e, 0xaa, 0x4f, 0x37, 0x2a, 0xb6, 0x5a,
	0x24, 0xaf, 0xa0, 0xe6, 0xe2, 0x67, 0xda, 0xf7, 0xa2, 0x76, 0xb6, 0xa1, 0xcf, 0x48, 0xa6, 0x95,
	0xa4, 0x77, 0x92, 0x69, 0x91, 0x37, 0xb0, 0xc6, 0xf1, 0x4b, 0x1f, 0x45, 0x84, 0x6e, 0x5b, 0x95,
	0x98, 0x95, 0x12, 0xab, 0xd7, 0xed, 0x93, 0x9b, 0x5a, 0xc9, 0x41, 0xa8, 0x5a, 0xe5, 0x58, 0x2b,
	0xe9, 0x29, 0x5a, 0x01, 0xd4, 0xf3, 0x3e, 0x69, 0x87, 0xc8, 0x7b, 0x4c, 0x08, 0x29, 0x5a, 0xa9,
	0x6b, 0x8d, 0xea, 0xce, 0x63, 0x2b, 0x3e, 0xd1, 0x23, 0xe6, 0x45, 0xc8, 0xad, 0x2c, 0xcb, 0x69,
	0x0a, 0xb6, 0x37, 0x72, 0x54, 0x32, 0x7d, 0xf2, 0x0e, 0x96, 0x06, 0x3b, 0x51, 0x04, 0x40, 0x0a,
	0xac, 0xab, 0x02, 0x83, 0xed, 0x64, 0x89, 0xff, 0xef, 0xab, 0x05, 0xb2, 0x0f, 0x7a, 0xf2, 0xdc,
	0x76, 0x02, 0x3f, 0xe2, 0x81, 0xd7, 0x16, 0x18, 0x45, 0xcc, 0xef, 0x0a, 0xbd, 0x2a, 0x7f, 0xf1,
	0x6a, 0xd2, 0x6f, 0xc5, 0xed, 0xb3, 0xa4, 0x4b, 0x1e, 0xc2, 0x3c, 0x75, 0x1c, 0x0c, 0x07, 0xe7,
	0x1b, 0x51, 0x47, 0x9f, 0xaf, 0x6b, 0x8d, 0xb2, 0x5d, 0x1d, 0xd6, 0xce, 0xa9, 0xf3, 0xbe, 0x54,
	0x9e, 0x5b, 0x2a, 0x9b, 0x35, 0x20, 0x19, 0xaf, 0xd8, 0xf1, 0xa9, 0x9b, 0x47, 0x50, 0x4b, 0x1e,
	0x9b, 0x8e, 0x83, 0x42, 0x24, 0x2f, 0xc4, 0x84, 0x79, 0xe5, 0xd8, 0x63, 0x53, 0x29, 0x35, 0x03,
	0xa0, 0x6c, 0xa3, 0x08, 0x03, 0x5f, 0xa0, 0x79, 0x0c, 0x46, 0x8b, 0xfa, 0x0e, 0x7a, 0x0a, 0xcd,
	0xbf, 0xb2, 0x6d, 0x81, 0x7e, 0x88, 0x1e, 0x46, 0x38, 0x3a, 0xb1, 0x82, 0xfb, 0xa9, 0x41, 0xfd,
	0x22, 0x74, 0x69, 0x84, 0x87, 0xa3, 0xde, 0x9b, 0x44, 0xfc, 0x6d, 0x4a, 0x5a, 0xe8, 0x72, 0xad,
	0xd0, 0xe5, 0xe6, 0x0f, 0x0d, 0x1e, 0xc5, 0x73, 0x7c, 0xc8, 0xdd, 0xd2, 0x70, 0x94, 0x55, 0x98,
	0xed, 0x4b, 0x58, 0x42, 0x96, 0xbc, 0x19, 0x87, 0x19, 0xf9, 0x71, 0x56, 0xd0, 0xc6, 0x59, 0xc1,
	0x3c, 0x86, 0x07, 0x4d, 0xb9, 0xf6, 0x73, 0xe4, 0x3d, 0xd1, 0xf4, 0xdd, 0x56, 0xe0, 0xbb, 0x4c,
	0xc6, 0x69, 0x38, 0xc0, 0x3a, 0x40, 0xec, 0x0c, 0xe9, 0x15, 0x4d, 0x7a, 0xa5, 0x12, 0x57, 0xce,
	0xa9, 0xa3, 0x9c, 0xad, 0x0d, 0x1b, 0xf1, 0x2e, 0x59, 0xc7, 0x43, 0x25, 0x9b, 0xc3, 0x4d, 0xbc,
	0xcc, 0x4c, 0x3d, 0x72, 0x81, 0x68, 0x39, 0x17, 0xc8, 0xce, 0xef, 0x39, 0xc5, 0x84, 0x67, 0xc8,
	0xbf, 0x32, 0x07, 0xc9, 0x91, 0x7a, 0x8d, 0x6d, 0x58, 0xe9, 0x7d, 0x67, 0xe5, 0x38, 0x60, 0xad,
	0xa0, 0x4f, 0x3e, 0xc1, 0x82, 0x62, 0x66, 0x52, 0xcf, 0x22, 0xf3, 0x7c, 0x6e, 0x3c, 0xb9, 0x0d,
	0x61, 0x5d, 0xff, 0x44, 0x1f, 0x56, 0x72, 0x2c, 0x4e, 0xb6, 0x94, 0x69, 0x0a, 0x33, 0x60, 0x6c,
	0xdf, 0x0d, 0x97, 0xea, 0x5d, 0xc2, 0xf2, 0x48, 0x08, 0xc8, 0x66, 0x96, 0xa5, 0x30, 0x23, 0x2f,
	0xee, 0x82, 0x4a, 0x95, 0xbe, 0x6b, 0x70, 0xaf, 0x30, 0x46, 0xe4, 0x79, 0x96, 0xec, 0xb6, 0xb4,
	0x19, 0x7b, 0x93, 0xa0, 0xd3, 0x11, 0x7e, 0x69, 0x70, 0x7f, 0x5c, 0x82, 0xc8, 0xf6, 0x28, 0xef,
	0xd8, 0xac, 0x19, 0xfb, 0x13, 0x7e, 0x90, 0xce, 0xf2, 0x0d, 0xf4, 0xa2, 0x1c, 0x91, 0x67, 0x59,
	0xd6, 0x5b, 0xd2, 0x66, 0xbc, 0x9e, 0x00, 0x9c, 0xca, 0x5f, 0xc1, 0x5a, 0x41, 0xf0, 0xc8, 0xd3,
	0x9b, 0x84, 0x63, 0xd2, 0xb9, 0x7b, 0x77, 0xec, 0xb5, 0xf6, 0xc1, 0x1e, 0x18, 0x5d, 0x2f, 0xe8,
	0x50, 0x2f, 0xf9, 0x98, 0x86, 0xcc, 0xea, 0xf2, 0xd0, 0x91, 0x2c, 0x07, 0x8b, 0x19, 0x13, 0x35,
	0x43, 0x76, 0xfa, 0xdf, 0xc7, 0x19, 0x09, 0xeb, 0xcc, 0xca, 0xff, 0x23, 0xbb, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x97, 0x2f, 0x0a, 0xe0, 0xbc, 0x08, 0x00, 0x00,
}
