// Code generated by protoc-gen-go.
// source: modem_transfer.proto
// DO NOT EDIT!

package hiber

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ModemTransfer_Type int32

const (
	ModemTransfer_TRANSFER ModemTransfer_Type = 0
	ModemTransfer_RETURN   ModemTransfer_Type = 1
)

var ModemTransfer_Type_name = map[int32]string{
	0: "TRANSFER",
	1: "RETURN",
}
var ModemTransfer_Type_value = map[string]int32{
	"TRANSFER": 0,
	"RETURN":   1,
}

func (x ModemTransfer_Type) String() string {
	return proto.EnumName(ModemTransfer_Type_name, int32(x))
}
func (ModemTransfer_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor7, []int{0, 0} }

type ModemTransfer_Status int32

const (
	ModemTransfer_IN_TRANSIT   ModemTransfer_Status = 0
	ModemTransfer_RECEIVED     ModemTransfer_Status = 1
	ModemTransfer_CANCELLED    ModemTransfer_Status = 3
	ModemTransfer_NOT_RECEIVED ModemTransfer_Status = 4
)

var ModemTransfer_Status_name = map[int32]string{
	0: "IN_TRANSIT",
	1: "RECEIVED",
	3: "CANCELLED",
	4: "NOT_RECEIVED",
}
var ModemTransfer_Status_value = map[string]int32{
	"IN_TRANSIT":   0,
	"RECEIVED":     1,
	"CANCELLED":    3,
	"NOT_RECEIVED": 4,
}

func (x ModemTransfer_Status) String() string {
	return proto.EnumName(ModemTransfer_Status_name, int32(x))
}
func (ModemTransfer_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor7, []int{0, 1} }

type ModemTransferReturnLine_Reason int32

const (
	ModemTransferReturnLine_OTHER                 ModemTransferReturnLine_Reason = 0
	ModemTransferReturnLine_INVALID_RECIPIENT     ModemTransferReturnLine_Reason = 1
	ModemTransferReturnLine_INVALID_CONFIGURATION ModemTransferReturnLine_Reason = 2
	ModemTransferReturnLine_DAMAGED               ModemTransferReturnLine_Reason = 3
	ModemTransferReturnLine_DEAD                  ModemTransferReturnLine_Reason = 4
	ModemTransferReturnLine_MISSING               ModemTransferReturnLine_Reason = 5
)

var ModemTransferReturnLine_Reason_name = map[int32]string{
	0: "OTHER",
	1: "INVALID_RECIPIENT",
	2: "INVALID_CONFIGURATION",
	3: "DAMAGED",
	4: "DEAD",
	5: "MISSING",
}
var ModemTransferReturnLine_Reason_value = map[string]int32{
	"OTHER":                 0,
	"INVALID_RECIPIENT":     1,
	"INVALID_CONFIGURATION": 2,
	"DAMAGED":               3,
	"DEAD":                  4,
	"MISSING":               5,
}

func (x ModemTransferReturnLine_Reason) String() string {
	return proto.EnumName(ModemTransferReturnLine_Reason_name, int32(x))
}
func (ModemTransferReturnLine_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor7, []int{1, 0}
}

type ModemTransfer struct {
	Identifier            string               `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	ModemNumbers          []string             `protobuf:"bytes,2,rep,name=modem_numbers,json=modemNumbers" json:"modem_numbers,omitempty"`
	Type                  ModemTransfer_Type   `protobuf:"varint,3,opt,name=type,enum=hiber.modem.ModemTransfer_Type" json:"type,omitempty"`
	Status                ModemTransfer_Status `protobuf:"varint,4,opt,name=status,enum=hiber.modem.ModemTransfer_Status" json:"status,omitempty"`
	SenderOrganization    string               `protobuf:"bytes,5,opt,name=sender_organization,json=senderOrganization" json:"sender_organization,omitempty"`
	RecipientOrganization string               `protobuf:"bytes,6,opt,name=recipient_organization,json=recipientOrganization" json:"recipient_organization,omitempty"`
	ReturnTransfers       []string             `protobuf:"bytes,7,rep,name=return_transfers,json=returnTransfers" json:"return_transfers,omitempty"`
	ReturnFor             []string             `protobuf:"bytes,8,rep,name=return_for,json=returnFor" json:"return_for,omitempty"`
	TrackingInformation   string               `protobuf:"bytes,9,opt,name=tracking_information,json=trackingInformation" json:"tracking_information,omitempty"`
	CreatedAt             *Timestamp           `protobuf:"bytes,10,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ReceivedAt            *Timestamp           `protobuf:"bytes,11,opt,name=received_at,json=receivedAt" json:"received_at,omitempty"`
	CancelledAt           *Timestamp           `protobuf:"bytes,12,opt,name=cancelled_at,json=cancelledAt" json:"cancelled_at,omitempty"`
	NotReceivedAt         *Timestamp           `protobuf:"bytes,13,opt,name=not_received_at,json=notReceivedAt" json:"not_received_at,omitempty"`
	ReturnDeadline        *Timestamp           `protobuf:"bytes,14,opt,name=return_deadline,json=returnDeadline" json:"return_deadline,omitempty"`
	Tags                  []*Tag               `protobuf:"bytes,15,rep,name=tags" json:"tags,omitempty"`
}

func (m *ModemTransfer) Reset()                    { *m = ModemTransfer{} }
func (m *ModemTransfer) String() string            { return proto.CompactTextString(m) }
func (*ModemTransfer) ProtoMessage()               {}
func (*ModemTransfer) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *ModemTransfer) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *ModemTransfer) GetModemNumbers() []string {
	if m != nil {
		return m.ModemNumbers
	}
	return nil
}

func (m *ModemTransfer) GetType() ModemTransfer_Type {
	if m != nil {
		return m.Type
	}
	return ModemTransfer_TRANSFER
}

func (m *ModemTransfer) GetStatus() ModemTransfer_Status {
	if m != nil {
		return m.Status
	}
	return ModemTransfer_IN_TRANSIT
}

func (m *ModemTransfer) GetSenderOrganization() string {
	if m != nil {
		return m.SenderOrganization
	}
	return ""
}

func (m *ModemTransfer) GetRecipientOrganization() string {
	if m != nil {
		return m.RecipientOrganization
	}
	return ""
}

func (m *ModemTransfer) GetReturnTransfers() []string {
	if m != nil {
		return m.ReturnTransfers
	}
	return nil
}

func (m *ModemTransfer) GetReturnFor() []string {
	if m != nil {
		return m.ReturnFor
	}
	return nil
}

func (m *ModemTransfer) GetTrackingInformation() string {
	if m != nil {
		return m.TrackingInformation
	}
	return ""
}

func (m *ModemTransfer) GetCreatedAt() *Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ModemTransfer) GetReceivedAt() *Timestamp {
	if m != nil {
		return m.ReceivedAt
	}
	return nil
}

func (m *ModemTransfer) GetCancelledAt() *Timestamp {
	if m != nil {
		return m.CancelledAt
	}
	return nil
}

func (m *ModemTransfer) GetNotReceivedAt() *Timestamp {
	if m != nil {
		return m.NotReceivedAt
	}
	return nil
}

func (m *ModemTransfer) GetReturnDeadline() *Timestamp {
	if m != nil {
		return m.ReturnDeadline
	}
	return nil
}

func (m *ModemTransfer) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ModemTransferReturnLine struct {
	OriginalTransfer string                         `protobuf:"bytes,1,opt,name=original_transfer,json=originalTransfer" json:"original_transfer,omitempty"`
	ReturnTransfer   string                         `protobuf:"bytes,2,opt,name=return_transfer,json=returnTransfer" json:"return_transfer,omitempty"`
	ModemNumbers     []string                       `protobuf:"bytes,3,rep,name=modem_numbers,json=modemNumbers" json:"modem_numbers,omitempty"`
	Reason           ModemTransferReturnLine_Reason `protobuf:"varint,4,opt,name=reason,enum=hiber.modem.ModemTransferReturnLine_Reason" json:"reason,omitempty"`
	Comment          string                         `protobuf:"bytes,5,opt,name=comment" json:"comment,omitempty"`
	CreatedAt        *Timestamp                     `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ReturnedAt       *Timestamp                     `protobuf:"bytes,7,opt,name=returned_at,json=returnedAt" json:"returned_at,omitempty"`
}

func (m *ModemTransferReturnLine) Reset()                    { *m = ModemTransferReturnLine{} }
func (m *ModemTransferReturnLine) String() string            { return proto.CompactTextString(m) }
func (*ModemTransferReturnLine) ProtoMessage()               {}
func (*ModemTransferReturnLine) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *ModemTransferReturnLine) GetOriginalTransfer() string {
	if m != nil {
		return m.OriginalTransfer
	}
	return ""
}

func (m *ModemTransferReturnLine) GetReturnTransfer() string {
	if m != nil {
		return m.ReturnTransfer
	}
	return ""
}

func (m *ModemTransferReturnLine) GetModemNumbers() []string {
	if m != nil {
		return m.ModemNumbers
	}
	return nil
}

func (m *ModemTransferReturnLine) GetReason() ModemTransferReturnLine_Reason {
	if m != nil {
		return m.Reason
	}
	return ModemTransferReturnLine_OTHER
}

func (m *ModemTransferReturnLine) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ModemTransferReturnLine) GetCreatedAt() *Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ModemTransferReturnLine) GetReturnedAt() *Timestamp {
	if m != nil {
		return m.ReturnedAt
	}
	return nil
}

type ModemTransferSelection struct {
	Identifiers   []string               `protobuf:"bytes,1,rep,name=identifiers" json:"identifiers,omitempty"`
	Modems        *ModemSelection        `protobuf:"bytes,2,opt,name=modems" json:"modems,omitempty"`
	Senders       []string               `protobuf:"bytes,3,rep,name=senders" json:"senders,omitempty"`
	Recipients    []string               `protobuf:"bytes,4,rep,name=recipients" json:"recipients,omitempty"`
	Statuses      []ModemTransfer_Status `protobuf:"varint,5,rep,packed,name=statuses,enum=hiber.modem.ModemTransfer_Status" json:"statuses,omitempty"`
	CreatedIn     *TimeRange             `protobuf:"bytes,6,opt,name=created_in,json=createdIn" json:"created_in,omitempty"`
	ReceivedIn    *TimeRange             `protobuf:"bytes,7,opt,name=received_in,json=receivedIn" json:"received_in,omitempty"`
	NotReceivedIn *TimeRange             `protobuf:"bytes,8,opt,name=not_received_in,json=notReceivedIn" json:"not_received_in,omitempty"`
	CancelledIn   *TimeRange             `protobuf:"bytes,9,opt,name=cancelled_in,json=cancelledIn" json:"cancelled_in,omitempty"`
	Types         []ModemTransfer_Type   `protobuf:"varint,10,rep,packed,name=types,enum=hiber.modem.ModemTransfer_Type" json:"types,omitempty"`
}

func (m *ModemTransferSelection) Reset()                    { *m = ModemTransferSelection{} }
func (m *ModemTransferSelection) String() string            { return proto.CompactTextString(m) }
func (*ModemTransferSelection) ProtoMessage()               {}
func (*ModemTransferSelection) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *ModemTransferSelection) GetIdentifiers() []string {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *ModemTransferSelection) GetModems() *ModemSelection {
	if m != nil {
		return m.Modems
	}
	return nil
}

func (m *ModemTransferSelection) GetSenders() []string {
	if m != nil {
		return m.Senders
	}
	return nil
}

func (m *ModemTransferSelection) GetRecipients() []string {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *ModemTransferSelection) GetStatuses() []ModemTransfer_Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *ModemTransferSelection) GetCreatedIn() *TimeRange {
	if m != nil {
		return m.CreatedIn
	}
	return nil
}

func (m *ModemTransferSelection) GetReceivedIn() *TimeRange {
	if m != nil {
		return m.ReceivedIn
	}
	return nil
}

func (m *ModemTransferSelection) GetNotReceivedIn() *TimeRange {
	if m != nil {
		return m.NotReceivedIn
	}
	return nil
}

func (m *ModemTransferSelection) GetCancelledIn() *TimeRange {
	if m != nil {
		return m.CancelledIn
	}
	return nil
}

func (m *ModemTransferSelection) GetTypes() []ModemTransfer_Type {
	if m != nil {
		return m.Types
	}
	return nil
}

type TransferModemsRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	// The ModemSelection is automatically appended with a status filter for 'in stock' modems. Modems with a different
	// status are ignored for the transfer.
	Selection *ModemSelection `protobuf:"bytes,2,opt,name=selection" json:"selection,omitempty"`
	// Existing organization to send the modems to.
	RecipientOrganization string `protobuf:"bytes,3,opt,name=recipient_organization,json=recipientOrganization" json:"recipient_organization,omitempty"`
	// Create a new organization to transfer the modems to.
	CreateRecipient *CreateOrganizationRequest `protobuf:"bytes,4,opt,name=create_recipient,json=createRecipient" json:"create_recipient,omitempty"`
	// Optional tracking information, like package tracking codes
	TrackingInformation string `protobuf:"bytes,5,opt,name=tracking_information,json=trackingInformation" json:"tracking_information,omitempty"`
}

func (m *TransferModemsRequest) Reset()                    { *m = TransferModemsRequest{} }
func (m *TransferModemsRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferModemsRequest) ProtoMessage()               {}
func (*TransferModemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *TransferModemsRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *TransferModemsRequest) GetSelection() *ModemSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

func (m *TransferModemsRequest) GetRecipientOrganization() string {
	if m != nil {
		return m.RecipientOrganization
	}
	return ""
}

func (m *TransferModemsRequest) GetCreateRecipient() *CreateOrganizationRequest {
	if m != nil {
		return m.CreateRecipient
	}
	return nil
}

func (m *TransferModemsRequest) GetTrackingInformation() string {
	if m != nil {
		return m.TrackingInformation
	}
	return ""
}

type TransferModemsRequest_Response struct {
	Request  *TransferModemsRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Transfer *ModemTransfer         `protobuf:"bytes,2,opt,name=transfer" json:"transfer,omitempty"`
}

func (m *TransferModemsRequest_Response) Reset()         { *m = TransferModemsRequest_Response{} }
func (m *TransferModemsRequest_Response) String() string { return proto.CompactTextString(m) }
func (*TransferModemsRequest_Response) ProtoMessage()    {}
func (*TransferModemsRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{3, 0}
}

func (m *TransferModemsRequest_Response) GetRequest() *TransferModemsRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *TransferModemsRequest_Response) GetTransfer() *ModemTransfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

type ListModemTransfersRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization string                  `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Selection    *ModemTransferSelection `protobuf:"bytes,2,opt,name=selection" json:"selection,omitempty"`
	Pagination   *Pagination             `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *ListModemTransfersRequest) Reset()                    { *m = ListModemTransfersRequest{} }
func (m *ListModemTransfersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListModemTransfersRequest) ProtoMessage()               {}
func (*ListModemTransfersRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *ListModemTransfersRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *ListModemTransfersRequest) GetSelection() *ModemTransferSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

func (m *ListModemTransfersRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListModemTransfersRequest_Response struct {
	Request    *ListModemTransfersRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Transfers  []*ModemTransfer           `protobuf:"bytes,2,rep,name=transfers" json:"transfers,omitempty"`
	Pagination *Pagination_Result         `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *ListModemTransfersRequest_Response) Reset()         { *m = ListModemTransfersRequest_Response{} }
func (m *ListModemTransfersRequest_Response) String() string { return proto.CompactTextString(m) }
func (*ListModemTransfersRequest_Response) ProtoMessage()    {}
func (*ListModemTransfersRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{4, 0}
}

func (m *ListModemTransfersRequest_Response) GetRequest() *ListModemTransfersRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ListModemTransfersRequest_Response) GetTransfers() []*ModemTransfer {
	if m != nil {
		return m.Transfers
	}
	return nil
}

func (m *ListModemTransfersRequest_Response) GetPagination() *Pagination_Result {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type CancelModemTransferRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization string                  `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Selection    *ModemTransferSelection `protobuf:"bytes,2,opt,name=selection" json:"selection,omitempty"`
}

func (m *CancelModemTransferRequest) Reset()                    { *m = CancelModemTransferRequest{} }
func (m *CancelModemTransferRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelModemTransferRequest) ProtoMessage()               {}
func (*CancelModemTransferRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *CancelModemTransferRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *CancelModemTransferRequest) GetSelection() *ModemTransferSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

type CancelModemTransferRequest_Response struct {
	Request   *CancelModemTransferRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Cancelled []*ModemTransfer            `protobuf:"bytes,2,rep,name=cancelled" json:"cancelled,omitempty"`
}

func (m *CancelModemTransferRequest_Response) Reset()         { *m = CancelModemTransferRequest_Response{} }
func (m *CancelModemTransferRequest_Response) String() string { return proto.CompactTextString(m) }
func (*CancelModemTransferRequest_Response) ProtoMessage()    {}
func (*CancelModemTransferRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{5, 0}
}

func (m *CancelModemTransferRequest_Response) GetRequest() *CancelModemTransferRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CancelModemTransferRequest_Response) GetCancelled() []*ModemTransfer {
	if m != nil {
		return m.Cancelled
	}
	return nil
}

type ReceivedModemTransferRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization string                  `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Selection    *ModemTransferSelection `protobuf:"bytes,2,opt,name=selection" json:"selection,omitempty"`
}

func (m *ReceivedModemTransferRequest) Reset()                    { *m = ReceivedModemTransferRequest{} }
func (m *ReceivedModemTransferRequest) String() string            { return proto.CompactTextString(m) }
func (*ReceivedModemTransferRequest) ProtoMessage()               {}
func (*ReceivedModemTransferRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

func (m *ReceivedModemTransferRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *ReceivedModemTransferRequest) GetSelection() *ModemTransferSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

type ReceivedModemTransferRequest_Response struct {
	Request  *ReceivedModemTransferRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Received []*ModemTransfer              `protobuf:"bytes,2,rep,name=received" json:"received,omitempty"`
}

func (m *ReceivedModemTransferRequest_Response) Reset()         { *m = ReceivedModemTransferRequest_Response{} }
func (m *ReceivedModemTransferRequest_Response) String() string { return proto.CompactTextString(m) }
func (*ReceivedModemTransferRequest_Response) ProtoMessage()    {}
func (*ReceivedModemTransferRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{6, 0}
}

func (m *ReceivedModemTransferRequest_Response) GetRequest() *ReceivedModemTransferRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ReceivedModemTransferRequest_Response) GetReceived() []*ModemTransfer {
	if m != nil {
		return m.Received
	}
	return nil
}

type NotReceivedModemTransferRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization string                  `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Selection    *ModemTransferSelection `protobuf:"bytes,2,opt,name=selection" json:"selection,omitempty"`
}

func (m *NotReceivedModemTransferRequest) Reset()                    { *m = NotReceivedModemTransferRequest{} }
func (m *NotReceivedModemTransferRequest) String() string            { return proto.CompactTextString(m) }
func (*NotReceivedModemTransferRequest) ProtoMessage()               {}
func (*NotReceivedModemTransferRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *NotReceivedModemTransferRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *NotReceivedModemTransferRequest) GetSelection() *ModemTransferSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

type NotReceivedModemTransferRequest_Response struct {
	Request     *NotReceivedModemTransferRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	NotReceived []*ModemTransfer                 `protobuf:"bytes,2,rep,name=not_received,json=notReceived" json:"not_received,omitempty"`
}

func (m *NotReceivedModemTransferRequest_Response) Reset() {
	*m = NotReceivedModemTransferRequest_Response{}
}
func (m *NotReceivedModemTransferRequest_Response) String() string { return proto.CompactTextString(m) }
func (*NotReceivedModemTransferRequest_Response) ProtoMessage()    {}
func (*NotReceivedModemTransferRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{7, 0}
}

func (m *NotReceivedModemTransferRequest_Response) GetRequest() *NotReceivedModemTransferRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *NotReceivedModemTransferRequest_Response) GetNotReceived() []*ModemTransfer {
	if m != nil {
		return m.NotReceived
	}
	return nil
}

type PrepareModemForReturnRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization string `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	// The transfer id that you received the modems with, to be used to the return.
	TransferId string `protobuf:"bytes,2,opt,name=transfer_id,json=transferId" json:"transfer_id,omitempty"`
	// Selection of modems, received from the transfer above.
	Selection *ModemSelection `protobuf:"bytes,3,opt,name=selection" json:"selection,omitempty"`
	// The reason for the return. For the 'other' reason, a comment is required.
	Reason ModemTransferReturnLine_Reason `protobuf:"varint,4,opt,name=reason,enum=hiber.modem.ModemTransferReturnLine_Reason" json:"reason,omitempty"`
	// Optional, unless the 'other' reason is selected.
	Comment string `protobuf:"bytes,5,opt,name=comment" json:"comment,omitempty"`
	// Use this to update the comment for a return line (using the same transfer_id and reason).
	ReplacePreviousComment bool `protobuf:"varint,6,opt,name=replace_previous_comment,json=replacePreviousComment" json:"replace_previous_comment,omitempty"`
}

func (m *PrepareModemForReturnRequest) Reset()                    { *m = PrepareModemForReturnRequest{} }
func (m *PrepareModemForReturnRequest) String() string            { return proto.CompactTextString(m) }
func (*PrepareModemForReturnRequest) ProtoMessage()               {}
func (*PrepareModemForReturnRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *PrepareModemForReturnRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *PrepareModemForReturnRequest) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *PrepareModemForReturnRequest) GetSelection() *ModemSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

func (m *PrepareModemForReturnRequest) GetReason() ModemTransferReturnLine_Reason {
	if m != nil {
		return m.Reason
	}
	return ModemTransferReturnLine_OTHER
}

func (m *PrepareModemForReturnRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *PrepareModemForReturnRequest) GetReplacePreviousComment() bool {
	if m != nil {
		return m.ReplacePreviousComment
	}
	return false
}

type PrepareModemForReturnRequest_Response struct {
	Request     *PrepareModemForReturnRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	ModemReturn *ModemTransferReturnLine      `protobuf:"bytes,2,opt,name=modem_return,json=modemReturn" json:"modem_return,omitempty"`
}

func (m *PrepareModemForReturnRequest_Response) Reset()         { *m = PrepareModemForReturnRequest_Response{} }
func (m *PrepareModemForReturnRequest_Response) String() string { return proto.CompactTextString(m) }
func (*PrepareModemForReturnRequest_Response) ProtoMessage()    {}
func (*PrepareModemForReturnRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{8, 0}
}

func (m *PrepareModemForReturnRequest_Response) GetRequest() *PrepareModemForReturnRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PrepareModemForReturnRequest_Response) GetModemReturn() *ModemTransferReturnLine {
	if m != nil {
		return m.ModemReturn
	}
	return nil
}

type DeleteModemTransferReturnLinesRequest struct {
	Organization string   `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	TransferId   string   `protobuf:"bytes,2,opt,name=transfer_id,json=transferId" json:"transfer_id,omitempty"`
	ModemNumbers []string `protobuf:"bytes,3,rep,name=modem_numbers,json=modemNumbers" json:"modem_numbers,omitempty"`
}

func (m *DeleteModemTransferReturnLinesRequest) Reset()         { *m = DeleteModemTransferReturnLinesRequest{} }
func (m *DeleteModemTransferReturnLinesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteModemTransferReturnLinesRequest) ProtoMessage()    {}
func (*DeleteModemTransferReturnLinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{9}
}

func (m *DeleteModemTransferReturnLinesRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *DeleteModemTransferReturnLinesRequest) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *DeleteModemTransferReturnLinesRequest) GetModemNumbers() []string {
	if m != nil {
		return m.ModemNumbers
	}
	return nil
}

type DeleteModemTransferReturnLinesRequest_Response struct {
}

func (m *DeleteModemTransferReturnLinesRequest_Response) Reset() {
	*m = DeleteModemTransferReturnLinesRequest_Response{}
}
func (m *DeleteModemTransferReturnLinesRequest_Response) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteModemTransferReturnLinesRequest_Response) ProtoMessage() {}
func (*DeleteModemTransferReturnLinesRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{9, 0}
}

type ListModemTransferReturnLinesRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization string                  `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Selection    *ModemTransferSelection `protobuf:"bytes,2,opt,name=selection" json:"selection,omitempty"`
	Pagination   *Pagination             `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *ListModemTransferReturnLinesRequest) Reset()         { *m = ListModemTransferReturnLinesRequest{} }
func (m *ListModemTransferReturnLinesRequest) String() string { return proto.CompactTextString(m) }
func (*ListModemTransferReturnLinesRequest) ProtoMessage()    {}
func (*ListModemTransferReturnLinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{10}
}

func (m *ListModemTransferReturnLinesRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *ListModemTransferReturnLinesRequest) GetSelection() *ModemTransferSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

func (m *ListModemTransferReturnLinesRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListModemTransferReturnLinesRequest_Response struct {
	Request    *ListModemTransferReturnLinesRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Lines      []*ModemTransferReturnLine           `protobuf:"bytes,2,rep,name=lines" json:"lines,omitempty"`
	Pagination *Pagination_Result                   `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *ListModemTransferReturnLinesRequest_Response) Reset() {
	*m = ListModemTransferReturnLinesRequest_Response{}
}
func (m *ListModemTransferReturnLinesRequest_Response) String() string {
	return proto.CompactTextString(m)
}
func (*ListModemTransferReturnLinesRequest_Response) ProtoMessage() {}
func (*ListModemTransferReturnLinesRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{10, 0}
}

func (m *ListModemTransferReturnLinesRequest_Response) GetRequest() *ListModemTransferReturnLinesRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ListModemTransferReturnLinesRequest_Response) GetLines() []*ModemTransferReturnLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *ListModemTransferReturnLinesRequest_Response) GetPagination() *Pagination_Result {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type SendReturnRequest struct {
	// Pick the organization to use (/impersonate). If unset, your default organization is used.
	Organization        string                  `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Selection           *ModemTransferSelection `protobuf:"bytes,2,opt,name=selection" json:"selection,omitempty"`
	TrackingInformation string                  `protobuf:"bytes,3,opt,name=tracking_information,json=trackingInformation" json:"tracking_information,omitempty"`
}

func (m *SendReturnRequest) Reset()                    { *m = SendReturnRequest{} }
func (m *SendReturnRequest) String() string            { return proto.CompactTextString(m) }
func (*SendReturnRequest) ProtoMessage()               {}
func (*SendReturnRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11} }

func (m *SendReturnRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *SendReturnRequest) GetSelection() *ModemTransferSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

func (m *SendReturnRequest) GetTrackingInformation() string {
	if m != nil {
		return m.TrackingInformation
	}
	return ""
}

type SendReturnRequest_Response struct {
	Request        *SendReturnRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	ReturnTransfer *ModemTransfer     `protobuf:"bytes,2,opt,name=return_transfer,json=returnTransfer" json:"return_transfer,omitempty"`
}

func (m *SendReturnRequest_Response) Reset()                    { *m = SendReturnRequest_Response{} }
func (m *SendReturnRequest_Response) String() string            { return proto.CompactTextString(m) }
func (*SendReturnRequest_Response) ProtoMessage()               {}
func (*SendReturnRequest_Response) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11, 0} }

func (m *SendReturnRequest_Response) GetRequest() *SendReturnRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SendReturnRequest_Response) GetReturnTransfer() *ModemTransfer {
	if m != nil {
		return m.ReturnTransfer
	}
	return nil
}

func init() {
	proto.RegisterType((*ModemTransfer)(nil), "hiber.modem.ModemTransfer")
	proto.RegisterType((*ModemTransferReturnLine)(nil), "hiber.modem.ModemTransferReturnLine")
	proto.RegisterType((*ModemTransferSelection)(nil), "hiber.modem.ModemTransferSelection")
	proto.RegisterType((*TransferModemsRequest)(nil), "hiber.modem.TransferModemsRequest")
	proto.RegisterType((*TransferModemsRequest_Response)(nil), "hiber.modem.TransferModemsRequest.Response")
	proto.RegisterType((*ListModemTransfersRequest)(nil), "hiber.modem.ListModemTransfersRequest")
	proto.RegisterType((*ListModemTransfersRequest_Response)(nil), "hiber.modem.ListModemTransfersRequest.Response")
	proto.RegisterType((*CancelModemTransferRequest)(nil), "hiber.modem.CancelModemTransferRequest")
	proto.RegisterType((*CancelModemTransferRequest_Response)(nil), "hiber.modem.CancelModemTransferRequest.Response")
	proto.RegisterType((*ReceivedModemTransferRequest)(nil), "hiber.modem.ReceivedModemTransferRequest")
	proto.RegisterType((*ReceivedModemTransferRequest_Response)(nil), "hiber.modem.ReceivedModemTransferRequest.Response")
	proto.RegisterType((*NotReceivedModemTransferRequest)(nil), "hiber.modem.NotReceivedModemTransferRequest")
	proto.RegisterType((*NotReceivedModemTransferRequest_Response)(nil), "hiber.modem.NotReceivedModemTransferRequest.Response")
	proto.RegisterType((*PrepareModemForReturnRequest)(nil), "hiber.modem.PrepareModemForReturnRequest")
	proto.RegisterType((*PrepareModemForReturnRequest_Response)(nil), "hiber.modem.PrepareModemForReturnRequest.Response")
	proto.RegisterType((*DeleteModemTransferReturnLinesRequest)(nil), "hiber.modem.DeleteModemTransferReturnLinesRequest")
	proto.RegisterType((*DeleteModemTransferReturnLinesRequest_Response)(nil), "hiber.modem.DeleteModemTransferReturnLinesRequest.Response")
	proto.RegisterType((*ListModemTransferReturnLinesRequest)(nil), "hiber.modem.ListModemTransferReturnLinesRequest")
	proto.RegisterType((*ListModemTransferReturnLinesRequest_Response)(nil), "hiber.modem.ListModemTransferReturnLinesRequest.Response")
	proto.RegisterType((*SendReturnRequest)(nil), "hiber.modem.SendReturnRequest")
	proto.RegisterType((*SendReturnRequest_Response)(nil), "hiber.modem.SendReturnRequest.Response")
	proto.RegisterEnum("hiber.modem.ModemTransfer_Type", ModemTransfer_Type_name, ModemTransfer_Type_value)
	proto.RegisterEnum("hiber.modem.ModemTransfer_Status", ModemTransfer_Status_name, ModemTransfer_Status_value)
	proto.RegisterEnum("hiber.modem.ModemTransferReturnLine_Reason", ModemTransferReturnLine_Reason_name, ModemTransferReturnLine_Reason_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ModemTransferService service

type ModemTransferServiceClient interface {
	// Transfer modems to a different organization.
	// As a result, the modem will get the outbound status for you, and the inbound status for the recipient.
	// Note: this call can automatically generate a child organization for the recipient if it has no organization.
	Transfer(ctx context.Context, in *TransferModemsRequest, opts ...grpc.CallOption) (*TransferModemsRequest_Response, error)
	// List transfers for modems. This could be used to list all active transfers on a selection of modems,
	// or, for example, to list this history of all transfers for one modem.
	List(ctx context.Context, in *ListModemTransfersRequest, opts ...grpc.CallOption) (*ListModemTransfersRequest_Response, error)
	// Cancel a started transfer.
	Cancel(ctx context.Context, in *CancelModemTransferRequest, opts ...grpc.CallOption) (*CancelModemTransferRequest_Response, error)
	// Mark inbound modems as received, adding them to your organization.
	Received(ctx context.Context, in *ReceivedModemTransferRequest, opts ...grpc.CallOption) (*ReceivedModemTransferRequest_Response, error)
	// Mark modems as not received when they were inbound but did not show up.
	// If you do receive the modems after marking them as not received, you can claim them to still get them in
	// your organization.
	NotReceived(ctx context.Context, in *NotReceivedModemTransferRequest, opts ...grpc.CallOption) (*NotReceivedModemTransferRequest_Response, error)
}

type modemTransferServiceClient struct {
	cc *grpc.ClientConn
}

func NewModemTransferServiceClient(cc *grpc.ClientConn) ModemTransferServiceClient {
	return &modemTransferServiceClient{cc}
}

func (c *modemTransferServiceClient) Transfer(ctx context.Context, in *TransferModemsRequest, opts ...grpc.CallOption) (*TransferModemsRequest_Response, error) {
	out := new(TransferModemsRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferService/Transfer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemTransferServiceClient) List(ctx context.Context, in *ListModemTransfersRequest, opts ...grpc.CallOption) (*ListModemTransfersRequest_Response, error) {
	out := new(ListModemTransfersRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemTransferServiceClient) Cancel(ctx context.Context, in *CancelModemTransferRequest, opts ...grpc.CallOption) (*CancelModemTransferRequest_Response, error) {
	out := new(CancelModemTransferRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferService/Cancel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemTransferServiceClient) Received(ctx context.Context, in *ReceivedModemTransferRequest, opts ...grpc.CallOption) (*ReceivedModemTransferRequest_Response, error) {
	out := new(ReceivedModemTransferRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferService/Received", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemTransferServiceClient) NotReceived(ctx context.Context, in *NotReceivedModemTransferRequest, opts ...grpc.CallOption) (*NotReceivedModemTransferRequest_Response, error) {
	out := new(NotReceivedModemTransferRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferService/NotReceived", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ModemTransferService service

type ModemTransferServiceServer interface {
	// Transfer modems to a different organization.
	// As a result, the modem will get the outbound status for you, and the inbound status for the recipient.
	// Note: this call can automatically generate a child organization for the recipient if it has no organization.
	Transfer(context.Context, *TransferModemsRequest) (*TransferModemsRequest_Response, error)
	// List transfers for modems. This could be used to list all active transfers on a selection of modems,
	// or, for example, to list this history of all transfers for one modem.
	List(context.Context, *ListModemTransfersRequest) (*ListModemTransfersRequest_Response, error)
	// Cancel a started transfer.
	Cancel(context.Context, *CancelModemTransferRequest) (*CancelModemTransferRequest_Response, error)
	// Mark inbound modems as received, adding them to your organization.
	Received(context.Context, *ReceivedModemTransferRequest) (*ReceivedModemTransferRequest_Response, error)
	// Mark modems as not received when they were inbound but did not show up.
	// If you do receive the modems after marking them as not received, you can claim them to still get them in
	// your organization.
	NotReceived(context.Context, *NotReceivedModemTransferRequest) (*NotReceivedModemTransferRequest_Response, error)
}

func RegisterModemTransferServiceServer(s *grpc.Server, srv ModemTransferServiceServer) {
	s.RegisterService(&_ModemTransferService_serviceDesc, srv)
}

func _ModemTransferService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferModemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferService/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferServiceServer).Transfer(ctx, req.(*TransferModemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemTransferService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModemTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferServiceServer).List(ctx, req.(*ListModemTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemTransferService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelModemTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferService/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferServiceServer).Cancel(ctx, req.(*CancelModemTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemTransferService_Received_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceivedModemTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferServiceServer).Received(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferService/Received",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferServiceServer).Received(ctx, req.(*ReceivedModemTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemTransferService_NotReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotReceivedModemTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferServiceServer).NotReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferService/NotReceived",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferServiceServer).NotReceived(ctx, req.(*NotReceivedModemTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModemTransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hiber.modem.ModemTransferService",
	HandlerType: (*ModemTransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _ModemTransferService_Transfer_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ModemTransferService_List_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _ModemTransferService_Cancel_Handler,
		},
		{
			MethodName: "Received",
			Handler:    _ModemTransferService_Received_Handler,
		},
		{
			MethodName: "NotReceived",
			Handler:    _ModemTransferService_NotReceived_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modem_transfer.proto",
}

// Client API for ModemTransferReturnService service

type ModemTransferReturnServiceClient interface {
	// If any problems are detected with the modems within the return period, mark them using this method.
	// Modems marked using this method can be returned in one transfer, as long as they are returned to the same
	// organization.
	Prepare(ctx context.Context, in *PrepareModemForReturnRequest, opts ...grpc.CallOption) (*PrepareModemForReturnRequest_Response, error)
	// List the return lines, either for a return transfer, or lines that have not been
	// returned with a return transfer yet.
	Lines(ctx context.Context, in *ListModemTransferReturnLinesRequest, opts ...grpc.CallOption) (*ListModemTransferReturnLinesRequest_Response, error)
	DeleteLine(ctx context.Context, in *DeleteModemTransferReturnLinesRequest, opts ...grpc.CallOption) (*DeleteModemTransferReturnLinesRequest_Response, error)
	// Transfer modems marked for return back to the sender.
	Send(ctx context.Context, in *SendReturnRequest, opts ...grpc.CallOption) (*SendReturnRequest_Response, error)
}

type modemTransferReturnServiceClient struct {
	cc *grpc.ClientConn
}

func NewModemTransferReturnServiceClient(cc *grpc.ClientConn) ModemTransferReturnServiceClient {
	return &modemTransferReturnServiceClient{cc}
}

func (c *modemTransferReturnServiceClient) Prepare(ctx context.Context, in *PrepareModemForReturnRequest, opts ...grpc.CallOption) (*PrepareModemForReturnRequest_Response, error) {
	out := new(PrepareModemForReturnRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferReturnService/Prepare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemTransferReturnServiceClient) Lines(ctx context.Context, in *ListModemTransferReturnLinesRequest, opts ...grpc.CallOption) (*ListModemTransferReturnLinesRequest_Response, error) {
	out := new(ListModemTransferReturnLinesRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferReturnService/Lines", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemTransferReturnServiceClient) DeleteLine(ctx context.Context, in *DeleteModemTransferReturnLinesRequest, opts ...grpc.CallOption) (*DeleteModemTransferReturnLinesRequest_Response, error) {
	out := new(DeleteModemTransferReturnLinesRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferReturnService/DeleteLine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemTransferReturnServiceClient) Send(ctx context.Context, in *SendReturnRequest, opts ...grpc.CallOption) (*SendReturnRequest_Response, error) {
	out := new(SendReturnRequest_Response)
	err := grpc.Invoke(ctx, "/hiber.modem.ModemTransferReturnService/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ModemTransferReturnService service

type ModemTransferReturnServiceServer interface {
	// If any problems are detected with the modems within the return period, mark them using this method.
	// Modems marked using this method can be returned in one transfer, as long as they are returned to the same
	// organization.
	Prepare(context.Context, *PrepareModemForReturnRequest) (*PrepareModemForReturnRequest_Response, error)
	// List the return lines, either for a return transfer, or lines that have not been
	// returned with a return transfer yet.
	Lines(context.Context, *ListModemTransferReturnLinesRequest) (*ListModemTransferReturnLinesRequest_Response, error)
	DeleteLine(context.Context, *DeleteModemTransferReturnLinesRequest) (*DeleteModemTransferReturnLinesRequest_Response, error)
	// Transfer modems marked for return back to the sender.
	Send(context.Context, *SendReturnRequest) (*SendReturnRequest_Response, error)
}

func RegisterModemTransferReturnServiceServer(s *grpc.Server, srv ModemTransferReturnServiceServer) {
	s.RegisterService(&_ModemTransferReturnService_serviceDesc, srv)
}

func _ModemTransferReturnService_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareModemForReturnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferReturnServiceServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferReturnService/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferReturnServiceServer).Prepare(ctx, req.(*PrepareModemForReturnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemTransferReturnService_Lines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModemTransferReturnLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferReturnServiceServer).Lines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferReturnService/Lines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferReturnServiceServer).Lines(ctx, req.(*ListModemTransferReturnLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemTransferReturnService_DeleteLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModemTransferReturnLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferReturnServiceServer).DeleteLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferReturnService/DeleteLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferReturnServiceServer).DeleteLine(ctx, req.(*DeleteModemTransferReturnLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemTransferReturnService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReturnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemTransferReturnServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hiber.modem.ModemTransferReturnService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemTransferReturnServiceServer).Send(ctx, req.(*SendReturnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModemTransferReturnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hiber.modem.ModemTransferReturnService",
	HandlerType: (*ModemTransferReturnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _ModemTransferReturnService_Prepare_Handler,
		},
		{
			MethodName: "Lines",
			Handler:    _ModemTransferReturnService_Lines_Handler,
		},
		{
			MethodName: "DeleteLine",
			Handler:    _ModemTransferReturnService_DeleteLine_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _ModemTransferReturnService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modem_transfer.proto",
}

func init() { proto.RegisterFile("modem_transfer.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 1548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x58, 0xdf, 0x6f, 0xdb, 0xd4,
	0x17, 0x5f, 0xe2, 0x24, 0x4d, 0x8e, 0xd3, 0xd6, 0xbd, 0x5b, 0xf7, 0xf5, 0xbc, 0x7d, 0xb7, 0xe0,
	0x01, 0xeb, 0x34, 0xc8, 0xb6, 0x54, 0x43, 0x2d, 0x30, 0x09, 0x2f, 0x49, 0x8b, 0x51, 0x97, 0x56,
	0x6e, 0x36, 0x21, 0x78, 0xb0, 0xdc, 0xe4, 0x36, 0xb3, 0x48, 0xec, 0x60, 0xdf, 0x56, 0x1a, 0x12,
	0x12, 0x6f, 0x88, 0x07, 0x40, 0xbc, 0xed, 0x01, 0xfe, 0x10, 0x1e, 0x90, 0x10, 0x0f, 0x3c, 0xed,
	0x89, 0x3f, 0x85, 0x27, 0x1e, 0x91, 0xef, 0xf5, 0xcf, 0x24, 0x4e, 0x1d, 0x18, 0x8c, 0xb7, 0xe6,
	0x9e, 0xcf, 0xb9, 0xe7, 0xdc, 0xcf, 0xf9, 0xe9, 0xc2, 0x85, 0x91, 0xdd, 0xc7, 0x23, 0x9d, 0x38,
	0x86, 0xe5, 0x1e, 0x63, 0xa7, 0x3e, 0x76, 0x6c, 0x62, 0x23, 0xfe, 0x89, 0x79, 0x84, 0x9d, 0x3a,
	0x95, 0x49, 0x70, 0x64, 0xb8, 0x98, 0x09, 0x24, 0x64, 0x3b, 0x03, 0xc3, 0x32, 0x3f, 0x33, 0x88,
	0x69, 0x5b, 0xfe, 0x19, 0x4f, 0x61, 0xfe, 0x8f, 0x0a, 0x31, 0x06, 0xec, 0x4f, 0xf9, 0xd7, 0x12,
	0x2c, 0x3f, 0xf4, 0x44, 0x5d, 0xff, 0x72, 0x74, 0x15, 0xc0, 0xec, 0x63, 0x8b, 0x98, 0xc7, 0x26,
	0x76, 0xc4, 0x5c, 0x2d, 0xb7, 0x51, 0xd1, 0x62, 0x27, 0xe8, 0x3a, 0x2c, 0x33, 0x77, 0xac, 0x93,
	0xd1, 0x11, 0x76, 0x5c, 0x31, 0x5f, 0xe3, 0x36, 0x2a, 0x5a, 0x95, 0x1e, 0x76, 0xd8, 0x19, 0xda,
	0x84, 0x02, 0x79, 0x3a, 0xc6, 0x22, 0x57, 0xcb, 0x6d, 0xac, 0x34, 0xae, 0xd5, 0x63, 0xae, 0xd6,
	0x13, 0xe6, 0xea, 0xdd, 0xa7, 0x63, 0xac, 0x51, 0x30, 0xda, 0x86, 0x92, 0x4b, 0x0c, 0x72, 0xe2,
	0x8a, 0x05, 0xaa, 0xf6, 0xca, 0x1c, 0xb5, 0x43, 0x0a, 0xd4, 0x7c, 0x05, 0x74, 0x1b, 0xce, 0xbb,
	0xd8, 0xea, 0x63, 0x47, 0x8f, 0xbf, 0x5d, 0x2c, 0x52, 0xef, 0x11, 0x13, 0xed, 0xc7, 0x24, 0xe8,
	0x1e, 0x5c, 0x74, 0x70, 0xcf, 0x1c, 0x9b, 0xd8, 0x22, 0x49, 0x9d, 0x12, 0xd5, 0x59, 0x0f, 0xa5,
	0x09, 0xb5, 0x9b, 0x20, 0x38, 0x98, 0x9c, 0x38, 0x56, 0x18, 0x0c, 0x57, 0x5c, 0xa2, 0xef, 0x5f,
	0x65, 0xe7, 0x81, 0x83, 0x2e, 0xfa, 0x3f, 0x80, 0x0f, 0x3d, 0xb6, 0x1d, 0xb1, 0x4c, 0x41, 0x15,
	0x76, 0xb2, 0x63, 0x3b, 0xe8, 0x2e, 0x5c, 0x20, 0x8e, 0xd1, 0xfb, 0xc4, 0xb4, 0x06, 0xba, 0x69,
	0x1d, 0xdb, 0xce, 0x88, 0x99, 0xaf, 0x50, 0xf3, 0xe7, 0x03, 0x99, 0x1a, 0x89, 0xd0, 0x6d, 0x80,
	0x9e, 0x83, 0x0d, 0x82, 0xfb, 0xba, 0x41, 0x44, 0xa8, 0xe5, 0x36, 0xf8, 0x86, 0xe0, 0x73, 0xd4,
	0x35, 0x47, 0xd8, 0x25, 0xc6, 0x68, 0xac, 0x55, 0x7c, 0x8c, 0x42, 0xd0, 0x5d, 0xe0, 0x1d, 0xdc,
	0xc3, 0xe6, 0x29, 0xd3, 0xe0, 0x53, 0x34, 0x20, 0x00, 0x29, 0x04, 0x6d, 0x42, 0xb5, 0x67, 0x58,
	0x3d, 0x3c, 0x1c, 0x32, 0x9d, 0x6a, 0x8a, 0x0e, 0x1f, 0xa2, 0x14, 0x82, 0xb6, 0x60, 0xd5, 0xb2,
	0x89, 0x1e, 0xb7, 0xb5, 0x9c, 0xa2, 0xb7, 0x6c, 0xd9, 0x44, 0x8b, 0xcc, 0x6d, 0x83, 0xcf, 0x9b,
	0xde, 0xc7, 0x46, 0x7f, 0x68, 0x5a, 0x58, 0x5c, 0x49, 0xd1, 0x5c, 0x61, 0xc0, 0x96, 0x8f, 0x43,
	0x32, 0x14, 0x88, 0x31, 0x70, 0xc5, 0xd5, 0x1a, 0xb7, 0xc1, 0x37, 0x56, 0x7c, 0xbc, 0x97, 0xd9,
	0x5d, 0x63, 0xa0, 0x51, 0x99, 0x5c, 0x83, 0x82, 0x97, 0x5f, 0xa8, 0x0a, 0xe5, 0xae, 0xa6, 0x74,
	0x0e, 0x77, 0xda, 0x9a, 0x70, 0x0e, 0x01, 0x94, 0xb4, 0x76, 0xf7, 0x91, 0xd6, 0x11, 0x72, 0xf2,
	0x2e, 0x94, 0x58, 0x2a, 0xa1, 0x15, 0x00, 0xb5, 0xa3, 0x53, 0x98, 0xda, 0x15, 0xce, 0x79, 0x3a,
	0x5a, 0xbb, 0xd9, 0x56, 0x1f, 0xb7, 0x5b, 0x42, 0x0e, 0x2d, 0x43, 0xa5, 0xa9, 0x74, 0x9a, 0xed,
	0xbd, 0xbd, 0x76, 0x4b, 0xe0, 0x90, 0x00, 0xd5, 0xce, 0x7e, 0x57, 0x0f, 0x01, 0x05, 0xf9, 0x17,
	0x0e, 0xfe, 0x97, 0x48, 0x51, 0x8d, 0xba, 0xbb, 0xe7, 0xb9, 0x7a, 0x0b, 0xd6, 0x6c, 0xc7, 0x1c,
	0x98, 0x96, 0x31, 0x0c, 0xf3, 0xc6, 0xaf, 0x2c, 0x21, 0x10, 0x84, 0xf5, 0x77, 0x23, 0xa4, 0x24,
	0x84, 0xe6, 0x29, 0x74, 0x25, 0x99, 0x61, 0xd3, 0x85, 0xc8, 0xcd, 0x28, 0xc4, 0x26, 0x94, 0x1c,
	0x6c, 0xb8, 0xb6, 0xe5, 0xd7, 0xd4, 0xad, 0xf4, 0x9a, 0x8a, 0x1c, 0xae, 0x6b, 0x54, 0x45, 0xf3,
	0x55, 0x91, 0x08, 0x4b, 0x3d, 0x7b, 0x34, 0xc2, 0x16, 0xf1, 0x2b, 0x2a, 0xf8, 0x39, 0x91, 0x92,
	0xa5, 0x8c, 0x29, 0xe9, 0xd9, 0x61, 0x1a, 0x4b, 0xe9, 0x29, 0xc9, 0x40, 0x0a, 0x91, 0x4d, 0x28,
	0x31, 0x7f, 0x50, 0x05, 0x8a, 0xfb, 0xdd, 0xf7, 0x69, 0x0c, 0xd7, 0x61, 0x4d, 0xed, 0x3c, 0x56,
	0xf6, 0xd4, 0x96, 0x17, 0x04, 0xf5, 0x40, 0x6d, 0x77, 0xba, 0x42, 0x0e, 0x5d, 0x82, 0xf5, 0xe0,
	0xb8, 0xb9, 0xdf, 0xd9, 0x51, 0x77, 0x1f, 0x69, 0x4a, 0x57, 0xdd, 0xef, 0x08, 0x79, 0xc4, 0xc3,
	0x52, 0x4b, 0x79, 0xa8, 0xec, 0xd2, 0xf8, 0x95, 0xa1, 0xd0, 0x6a, 0x2b, 0x2d, 0xa1, 0xe0, 0x1d,
	0x3f, 0x54, 0x0f, 0x0f, 0xd5, 0xce, 0xae, 0x50, 0x94, 0x7f, 0xe7, 0xe0, 0x62, 0x82, 0x93, 0x43,
	0x3c, 0xc4, 0x3d, 0x5a, 0x7c, 0x35, 0xe0, 0xa3, 0x26, 0xe8, 0x8a, 0x39, 0xca, 0x75, 0xfc, 0x08,
	0x6d, 0x42, 0x89, 0xb2, 0xea, 0xd2, 0x78, 0xf1, 0x8d, 0xcb, 0xd3, 0x54, 0x87, 0xd7, 0x69, 0x3e,
	0xd4, 0xa3, 0x96, 0x75, 0xa7, 0x20, 0x7c, 0xc1, 0x4f, 0xaf, 0x0f, 0x87, 0x3d, 0xc8, 0xeb, 0x88,
	0x9e, 0x30, 0x76, 0x82, 0xee, 0x43, 0x99, 0x35, 0x3f, 0xec, 0x8a, 0xc5, 0x1a, 0x97, 0xad, 0x5f,
	0x86, 0x2a, 0xf1, 0xc8, 0x99, 0xd6, 0x8c, 0xc8, 0x69, 0x86, 0x35, 0xc0, 0x61, 0xe4, 0x54, 0x2b,
	0xd1, 0x4c, 0x4c, 0x6b, 0x46, 0xe4, 0x98, 0x46, 0xd8, 0x4c, 0x54, 0x6b, 0xaa, 0x2f, 0x98, 0x96,
	0x58, 0x4e, 0x51, 0x8b, 0xf7, 0x05, 0xd5, 0x4a, 0xb6, 0x21, 0x93, 0x75, 0xc5, 0x59, 0x6a, 0x51,
	0x1b, 0x52, 0xbd, 0x9e, 0x5e, 0xf4, 0xe6, 0x88, 0x2b, 0x02, 0xa5, 0xe3, 0xcc, 0xa9, 0xc3, 0xd0,
	0xf2, 0x4f, 0x1c, 0xac, 0x07, 0x02, 0x8a, 0x72, 0x35, 0xfc, 0xe9, 0x09, 0x76, 0x09, 0x92, 0xa1,
	0x9a, 0x18, 0x0d, 0xac, 0x64, 0x13, 0x67, 0x68, 0x1b, 0x2a, 0x6e, 0x10, 0xd5, 0x2c, 0x81, 0x8f,
	0xd0, 0x73, 0x66, 0x10, 0x37, 0x6f, 0x06, 0x7d, 0x08, 0x02, 0x8b, 0x8a, 0x1e, 0xca, 0x69, 0x71,
	0xf3, 0x8d, 0x37, 0x7d, 0xc3, 0x89, 0xf9, 0xdf, 0xa4, 0xd8, 0xf8, 0x0d, 0xfe, 0xf3, 0xb4, 0x55,
	0x76, 0x8d, 0x16, 0xdc, 0x92, 0x3a, 0x93, 0x8a, 0xa9, 0x33, 0x49, 0xfa, 0x22, 0x07, 0x65, 0x0d,
	0xbb, 0x63, 0xdb, 0x72, 0x31, 0x7a, 0x17, 0x96, 0x1c, 0x76, 0x37, 0xa5, 0x8a, 0x6f, 0xc8, 0x09,
	0x26, 0x66, 0x92, 0xac, 0x05, 0x2a, 0xe8, 0x2d, 0x28, 0x27, 0x3a, 0x1e, 0xdf, 0x90, 0xe6, 0x34,
	0xab, 0x10, 0x2b, 0xff, 0x91, 0x87, 0x4b, 0x7b, 0xa6, 0x4b, 0x12, 0xf2, 0x85, 0x62, 0xa8, 0x4c,
	0xc7, 0xf0, 0x7a, 0xba, 0xe9, 0x99, 0xb1, 0xbc, 0x0b, 0x30, 0x36, 0xbc, 0x46, 0x1e, 0xc6, 0x8f,
	0x6f, 0xac, 0xf9, 0x77, 0x1c, 0x84, 0x02, 0x2d, 0x06, 0x92, 0x7e, 0x8e, 0x53, 0xf7, 0xde, 0x24,
	0x75, 0xaf, 0x27, 0x1c, 0x48, 0x7d, 0x5f, 0x44, 0xdf, 0x16, 0x54, 0xa2, 0x9d, 0x24, 0x4f, 0x87,
	0xe2, 0x3c, 0xfe, 0x22, 0x30, 0xda, 0x9a, 0xe1, 0xbb, 0x38, 0xe5, 0x7b, 0x5d, 0xc3, 0xee, 0xc9,
	0x90, 0xc4, 0x9f, 0x20, 0x7f, 0x9d, 0x07, 0xa9, 0x49, 0x2b, 0x70, 0x62, 0x92, 0xfc, 0x9b, 0xdc,
	0x4b, 0x5f, 0xc6, 0x89, 0x54, 0x26, 0x89, 0xbc, 0x91, 0xb8, 0x2d, 0xdd, 0xdb, 0x04, 0x93, 0x61,
	0x5b, 0xc9, 0xc2, 0x64, 0x08, 0x96, 0xbf, 0xcd, 0xc3, 0x95, 0xa0, 0x8b, 0xfd, 0x67, 0x18, 0x69,
	0x4e, 0x32, 0x72, 0x33, 0x71, 0xdb, 0x3c, 0x7f, 0x13, 0xc5, 0x19, 0xb4, 0xf1, 0x0c, 0x94, 0x84,
	0x58, 0xf9, 0xfb, 0x3c, 0x5c, 0xeb, 0x44, 0xad, 0xfd, 0x65, 0x92, 0xf2, 0x5d, 0x9c, 0x94, 0x9d,
	0x49, 0x52, 0xde, 0x48, 0xdc, 0x76, 0x86, 0xcb, 0x11, 0x2f, 0xf7, 0xa1, 0x1a, 0x1f, 0x71, 0x19,
	0xb8, 0xe1, 0x63, 0x93, 0x4e, 0xfe, 0x8d, 0x83, 0x2b, 0x07, 0x0e, 0x1e, 0x1b, 0x0e, 0xa6, 0xa8,
	0x1d, 0xdb, 0x5f, 0xc3, 0x16, 0xe1, 0xe6, 0x1a, 0xf0, 0x41, 0x31, 0xeb, 0x66, 0xdf, 0xdf, 0x16,
	0x21, 0x38, 0x52, 0xfb, 0xc9, 0x19, 0xc5, 0x2d, 0x34, 0xa3, 0xfe, 0xe1, 0xfd, 0x71, 0x0b, 0x44,
	0x07, 0x8f, 0x87, 0x46, 0x0f, 0xeb, 0x63, 0x07, 0x9f, 0x9a, 0xf6, 0x89, 0xab, 0x07, 0x50, 0x6f,
	0x27, 0x29, 0x6b, 0x17, 0x7d, 0xf9, 0x81, 0x2f, 0x6e, 0x32, 0xa9, 0xf4, 0x6c, 0x81, 0x14, 0x9f,
	0xc7, 0x70, 0x14, 0xca, 0x5d, 0x60, 0xab, 0xb3, 0xce, 0x76, 0x4f, 0x3f, 0xcb, 0x5e, 0xcd, 0xf2,
	0x60, 0x8d, 0x7d, 0x5e, 0xb3, 0x03, 0xf9, 0x87, 0x1c, 0xbc, 0xd6, 0xc2, 0x43, 0x4c, 0x70, 0x0a,
	0xdc, 0x7d, 0xa1, 0xd1, 0xcd, 0xf2, 0x1d, 0x20, 0x41, 0xc4, 0x96, 0xfc, 0x0d, 0x07, 0xd7, 0xa7,
	0x06, 0xca, 0x5f, 0xf4, 0xee, 0xe5, 0x8c, 0xce, 0xe7, 0xf1, 0xe0, 0x7f, 0x30, 0x19, 0xfc, 0x3b,
	0xf3, 0x47, 0xe7, 0xf4, 0x4b, 0xa3, 0x1c, 0x78, 0x1b, 0x8a, 0xde, 0xc7, 0x65, 0x30, 0x40, 0xb3,
	0x05, 0x9f, 0xa9, 0xfc, 0x8d, 0x31, 0xfa, 0x63, 0x1e, 0xd6, 0x0e, 0xb1, 0xd5, 0x5f, 0xbc, 0xf4,
	0x5f, 0x08, 0xfd, 0xb3, 0x97, 0x3e, 0x2e, 0x7d, 0xe9, 0xfb, 0x2a, 0x4e, 0xff, 0xd6, 0x24, 0xfd,
	0x57, 0x13, 0x0e, 0x4c, 0xbd, 0x2b, 0x22, 0xbb, 0x39, 0xfb, 0x4b, 0x77, 0x7e, 0xfb, 0x9c, 0xf8,
	0x0a, 0x6e, 0x3c, 0x2b, 0xc0, 0x85, 0x89, 0x47, 0x3a, 0xa7, 0x66, 0x0f, 0xa3, 0x8f, 0xa1, 0x1c,
	0x7e, 0x2a, 0x67, 0xd8, 0x43, 0xa5, 0x5b, 0x67, 0x63, 0xea, 0xe1, 0xa3, 0x75, 0x28, 0x78, 0x79,
	0x85, 0x32, 0x6e, 0x69, 0xd2, 0xed, 0x6c, 0xb8, 0xc8, 0x40, 0x0f, 0x4a, 0x6c, 0x55, 0x41, 0x59,
	0xf7, 0x17, 0xe9, 0x4e, 0x46, 0x60, 0x64, 0xc4, 0xf4, 0xc2, 0xc8, 0x26, 0x11, 0xca, 0xbe, 0x14,
	0x48, 0x8d, 0xcc, 0xd0, 0xc8, 0x94, 0x03, 0x7c, 0x6c, 0xa6, 0xa2, 0x85, 0xa6, 0xad, 0x74, 0x6f,
	0x11, 0x74, 0x68, 0xb3, 0xf1, 0x9c, 0x03, 0x69, 0x46, 0xcd, 0x06, 0x09, 0xf2, 0x04, 0x96, 0xfc,
	0xc1, 0x80, 0xb2, 0x8f, 0x8b, 0x89, 0xc7, 0xcf, 0x83, 0x46, 0x8f, 0x27, 0x50, 0xa4, 0xed, 0x06,
	0x2d, 0xdc, 0x99, 0xa4, 0xed, 0x45, 0x35, 0x22, 0xab, 0x9f, 0x03, 0xb0, 0x29, 0x44, 0xff, 0x07,
	0x95, 0xf4, 0x3b, 0xd3, 0x78, 0x92, 0xde, 0x59, 0x5c, 0x27, 0x32, 0xbf, 0x0f, 0x05, 0xaf, 0xf6,
	0xd1, 0x19, 0xed, 0x40, 0xba, 0x31, 0x5f, 0x1e, 0x5e, 0xf8, 0x60, 0x0b, 0x2e, 0x0f, 0x86, 0xf6,
	0x91, 0x31, 0xf4, 0x15, 0x8c, 0xb1, 0x59, 0x1f, 0x38, 0xe3, 0x1e, 0xd3, 0x7c, 0x20, 0x24, 0x3c,
	0x53, 0xc6, 0xe6, 0xc1, 0xb9, 0x8f, 0x8a, 0x14, 0x79, 0x54, 0xa2, 0xff, 0xeb, 0xde, 0xfc, 0x33,
	0x00, 0x00, 0xff, 0xff, 0x8f, 0x76, 0xac, 0x26, 0x48, 0x17, 0x00, 0x00,
}
